public class TestThrowandThrows{
    public static void method() throws ArithmeticException
    {
            System.out.println("Inside the method()");
            throw new ArithmeticException("\nAccess denie- You must be atleast 18 years old.");
    }
    public static void main (String[] args) {
    try {
        method();
    } catch(ArithmeticException e) {
         System.out.println("\nCaught in main() method");
    }
    
   
    
    }
}
